# -*- coding: utf-8 -*-
"""
Created on Tue Nov 13 22:32:47 2018

@author: Giorgia
"""
import numpy as np

# This script contains a function that returns a list with the name of the files and the corresponding labels
def define_data_and_labels(which_dataset):
    ctl_list_norm = ['CTL1_tono_voi_onRef_PAC_RH.txt','CTL1_tono_voi_onRef_PAC_LH.txt',
                 'CTL2_tono_voi_onRef_PAC_RH.txt','CTL2_tono_voi_onRef_PAC_LH.txt',
                 'CTL3_tono_voi_onRef_PAC_RH.txt','CTL3_tono_voi_onRef_PAC_LH.txt',
                 'CTL4_tono_voi_onRef_PAC_RH.txt','CTL4_tono_voi_onRef_PAC_LH.txt',
                 'CTL5_tono_voi_onRef_PAC_RH.txt','CTL5_tono_voi_onRef_PAC_LH.txt',
                 'CTL6_tono_voi_onRef_PAC_RH.txt','CTL6_tono_voi_onRef_PAC_LH.txt',
                 'CTL7_tono_voi_onRef_PAC_RH.txt','CTL7_tono_voi_onRef_PAC_LH.txt',
                 'CTL8_tono_voi_onRef_PAC_RH.txt','CTL8_tono_voi_onRef_PAC_LH.txt',
                 'CTL9_tono_voi_onRef_PAC_RH.txt','CTL9_tono_voi_onRef_PAC_LH.txt',
                 'CTL10_tono_voi_onRef_PAC_RH.txt','CTL10_tono_voi_onRef_PAC_LH.txt',
                 'CTL12_tono_voi_onRef_PAC_RH.txt','CTL12_tono_voi_onRef_PAC_LH.txt',
                 'CTL13_tono_voi_onRef_PAC_RH.txt','CTL13_tono_voi_onRef_PAC_LH.txt']

    pt_list_norm = ['PT1_tono_voi_onRef_PAC_RH.txt','PT1_tono_voi_onRef_PAC_LH.txt',
               'PT2_tono_voi_onRef_PAC_RH.txt','PT2_tono_voi_onRef_PAC_LH.txt',
               'PT3_tono_voi_onRef_PAC_RH.txt','PT3_tono_voi_onRef_PAC_LH.txt',
               'PT4_tono_voi_onRef_PAC_RH.txt','PT4_tono_voi_onRef_PAC_LH.txt',
               'PT5_tono_voi_onRef_PAC_RH.txt','PT5_tono_voi_onRef_PAC_LH.txt',
               'PT6_tono_voi_onRef_PAC_RH.txt','PT6_tono_voi_onRef_PAC_LH.txt',
               'PT7_tono_voi_onRef_PAC_RH.txt','PT7_tono_voi_onRef_PAC_LH.txt',
               'PT8_tono_voi_onRef_PAC_RH.txt','PT8_tono_voi_onRef_PAC_LH.txt',
               'PT9_tono_voi_onRef_PAC_RH.txt','PT9_tono_voi_onRef_PAC_LH.txt',
               'PT10_tono_voi_onRef_PAC_RH.txt','PT10_tono_voi_onRef_PAC_LH.txt',
               'PT11_tono_voi_onRef_PAC_RH.txt','PT11_tono_voi_onRef_PAC_LH.txt',
               'PT12_tono_voi_onRef_PAC_RH.txt','PT12_tono_voi_onRef_PAC_LH.txt',
               'PT13_tono_voi_onRef_PAC_RH.txt','PT13_tono_voi_onRef_PAC_LH.txt',
               'PT14_tono_voi_onRef_PAC_RH.txt','PT14_tono_voi_onRef_PAC_LH.txt',
               'PT15_tono_voi_onRef_PAC_RH.txt','PT15_tono_voi_onRef_PAC_LH.txt',
               'PT16_tono_voi_onRef_PAC_RH.txt','PT16_tono_voi_onRef_PAC_LH.txt',
               'PT17_tono_voi_onRef_PAC_RH.txt','PT17_tono_voi_onRef_PAC_LH.txt',
               'PT18_tono_voi_onRef_PAC_RH.txt','PT18_tono_voi_onRef_PAC_LH.txt',
               'PT19_tono_voi_onRef_PAC_RH.txt','PT19_tono_voi_onRef_PAC_LH.txt',
               'PT20_tono_voi_onRef_PAC_RH.txt','PT20_tono_voi_onRef_PAC_LH.txt',
               'PT21_tono_voi_onRef_PAC_RH.txt','PT21_tono_voi_onRef_PAC_LH.txt',
               'PT22_tono_voi_onRef_PAC_RH.txt','PT22_tono_voi_onRef_PAC_LH.txt',
               'PT23_tono_voi_onRef_PAC_RH.txt','PT23_tono_voi_onRef_PAC_LH.txt',
               'PT24_tono_voi_onRef_PAC_RH.txt','PT24_tono_voi_onRef_PAC_LH.txt']
    ctl_name_norm = ['Control 1 - RH','Control 1 - LH',
                'Control 2 - RH','Control 2 - LH',
                'Control 3 - RH','Control 3 - LH',
                'Control 4 - RH','Control 4 - LH',
                'Control 5 - RH','Control 5 - LH',
                'Control 6 - RH','Control 6 - LH',
                'Control 7 - RH','Control 7 - LH',
                'Control 8 - RH','Control 8 - LH',
                'Control 9 - RH','Control 9 - LH',
                'Control 10 - RH','Control 10 - LH',
                'Control 12 - RH','Control 12 - LH',
                'Control 13 - RH','Control 13 - LH']
    
    pt_name_norm = ['Patient 1 - RH', 'Patient 1 - LH',
               'Patient 2 - RH', 'Patient 2 - LH',
               'Patient 3 - RH', 'Patient 3 - LH',
               'Patient 4 - RH', 'Patient 4 - LH',
               'Patient 5 - RH', 'Patient 5 - LH',
               'Patient 6 - RH', 'Patient 6 - LH',
               'Patient 7 - RH', 'Patient 7 - LH',
               'Patient 8 - RH', 'Patient 8 - LH',
               'Patient 9 - RH', 'Patient 9 - LH',
               'Patient 10 - RH', 'Patient 10 - LH',
               'Patient 11 - RH', 'Patient 11 - LH',
               'Patient 12 - RH', 'Patient 12 - LH',
               'Patient 13 - RH', 'Patient 13 - LH',
               'Patient 14 - RH', 'Patient 14 - LH',
               'Patient 15 - RH', 'Patient 15 - LH',
               'Patient 16 - RH', 'Patient 16 - LH',
               'Patient 17 - RH', 'Patient 17 - LH',
               'Patient 18 - RH', 'Patient 18 - LH',
               'Patient 19 - RH', 'Patient 19 - LH',
               'Patient 20 - RH', 'Patient 20 - LH',
               'Patient 21 - RH', 'Patient 21 - LH',
               'Patient 22 - RH', 'Patient 22 - LH',
               'Patient 23 - RH', 'Patient 23 - LH',
               'Patient 24 - RH', 'Patient 24 - LH']
    
    ctl_list_full = ['CTL1_tono_poi_PAC_RH', 'CTL1_tono_poi_PAC_LH',
                     'CTL2_tono_poi_PAC_RH', 'CTL2_tono_poi_PAC_LH',
                     'CTL3_tono_poi_PAC_RH', 'CTL3_tono_poi_PAC_LH',
                     'CTL4_tono_poi_PAC_RH', 'CTL4_tono_poi_PAC_LH',
                     'CTL5_tono_poi_PAC_RH', 'CTL5_tono_poi_PAC_LH',
                     'CTL6_tono_poi_PAC_RH', 'CTL6_tono_poi_PAC_LH',
                     'CTL7_tono_poi_PAC_RH', 'CTL7_tono_poi_PAC_LH',
                     'CTL8_tono_poi_PAC_RH', 'CTL8_tono_poi_PAC_LH',
                     'CTL9_tono_poi_PAC_RH', 'CTL9_tono_poi_PAC_LH',
                     'CTL10_tono_poi_PAC_RH', 'CTL10_tono_poi_PAC_LH',
                     'CTL12_tono_poi_PAC_RH', 'CTL12_tono_poi_PAC_LH']
    
    pt_list_full = ['PT1_tono_poi_PAC_RH', 'PT1_tono_poi_PAC_LH',
                    'PT2_tono_poi_PAC_RH', 
                    'PT3_tono_poi_PAC_RH',
                    'PT4_tono_poi_PAC_RH', 'PT4_tono_poi_PAC_LH',
                    'PT5_tono_poi_PAC_RH', 'PT5_tono_poi_PAC_LH',
                    'PT6_tono_poi_PAC_LH',
                    'PT7_tono_poi_PAC_LH',
                    'PT8_tono_poi_PAC_RH', 'PT8_tono_poi_PAC_LH',
                    'PT9_tono_poi_PAC_RH', 'PT9_tono_poi_PAC_LH',
                    'PT10_tono_poi_PAC_LH',
                    'PT11_tono_poi_PAC_RH', 'PT11_tono_poi_PAC_LH',
                    'PT12_tono_poi_PAC_RH', 'PT12_tono_poi_PAC_LH',
                    'PT13_tono_poi_PAC_RH', 'PT13_tono_poi_PAC_LH',
                    'PT14_tono_poi_PAC_LH',
                    'PT15_tono_poi_PAC_RH', 'PT15_tono_poi_PAC_LH',
                    'PT16_tono_poi_PAC_RH', 'PT16_tono_poi_PAC_LH',
                    'PT17_tono_poi_PAC_RH', 'PT17_tono_poi_PAC_LH',
                    'PT18_tono_poi_PAC_RH',
                    'PT19_tono_poi_PAC_LH',
                    'PT20_tono_poi_PAC_RH', 'PT20_tono_poi_PAC_LH',
                    'PT21_tono_poi_PAC_RH',
                    'PT22_tono_poi_PAC_RH',
                    'PT23_tono_poi_PAC_LH',
                    'PT24_tono_poi_PAC_RH'] # careful we're missing PT2LH,PT3LH,PT6RH,PT7RH,PT10RH,PT14RH,PT18LH,PT19RH,PT21LH,PT22LH,PT23RH,PT24LH

    ctl_name_full = ['Control 1 - RH','Control 1 - LH',
                'Control 2 - RH','Control 2 - LH',
                'Control 3 - RH','Control 3 - LH',
                'Control 4 - RH','Control 4 - LH',
                'Control 5 - RH','Control 5 - LH',
                'Control 6 - RH','Control 6 - LH',
                'Control 7 - RH','Control 7 - LH',
                'Control 8 - RH','Control 8 - LH',
                'Control 9 - RH','Control 9 - LH',
                'Control 10 - RH','Control 10 - LH',
                'Control 12 - RH','Control 12 - LH',
                'Control 13 - RH','Control 13 - LH']
    
    pt_name_full = ['Patient 1 - RH', 'Patient 1 - LH',
               'Patient 2 - RH', 
               'Patient 3 - RH', 
               'Patient 4 - RH', 'Patient 4 - LH',
               'Patient 5 - RH', 'Patient 5 - LH',
               'Patient 6 - LH',
               'Patient 7 - LH',
               'Patient 8 - RH', 'Patient 8 - LH',
               'Patient 9 - RH', 'Patient 9 - LH',
               'Patient 10 - LH',
               'Patient 11 - RH', 'Patient 11 - LH',
               'Patient 12 - RH', 'Patient 12 - LH',
               'Patient 13 - RH', 'Patient 13 - LH',
               'Patient 14 - LH',
               'Patient 15 - RH', 'Patient 15 - LH',
               'Patient 16 - RH', 'Patient 16 - LH',
               'Patient 17 - RH', 'Patient 17 - LH',
               'Patient 18 - RH',
               'Patient 19 - LH',
               'Patient 20 - RH', 'Patient 20 - LH',
               'Patient 21 - RH',
               'Patient 22 - RH',
               'Patient 23 - LH',
               'Patient 24 - RH']

    
    ctl_anat_full = ['CTL1_anat_poi_PAC_RH', 'CTL1_anat_poi_PAC_LH',
                'CTL2_anat_poi_PAC_RH', 'CTL2_anat_poi_PAC_LH',
                'CTL3_anat_poi_PAC_RH', 'CTL3_anat_poi_PAC_LH',
                'CTL4_anat_poi_PAC_RH', 'CTL4_anat_poi_PAC_LH',
                'CTL5_anat_poi_PAC_RH', 'CTL5_anat_poi_PAC_LH',
                'CTL6_anat_poi_PAC_RH', 'CTL6_anat_poi_PAC_LH',
                'CTL7_anat_poi_PAC_RH', 'CTL7_anat_poi_PAC_LH',
                'CTL8_anat_poi_PAC_RH', 'CTL8_anat_poi_PAC_LH',
                'CTL9_anat_poi_PAC_RH', 'CTL9_anat_poi_PAC_LH',
                'CTL10_anat_poi_PAC_RH', 'CTL10_anat_poi_PAC_LH',
                'CTL12_anat_poi_PAC_RH', 'CTL12_anat_poi_PAC_LH']

    pt_anat_full = ['PT1_anat_poi_PAC_RH', 'PT1_anat_poi_PAC_LH',
               'PT2_anat_poi_PAC_RH', 
               'PT3_anat_poi_PAC_RH',
               'PT4_anat_poi_PAC_RH', 'PT4_anat_poi_PAC_LH',
               'PT5_anat_poi_PAC_RH', 'PT5_anat_poi_PAC_LH',
               'PT6_anat_poi_PAC_LH',
               'PT7_anat_poi_PAC_LH',
               'PT8_anat_poi_PAC_RH', 'PT8_anat_poi_PAC_LH',
               'PT9_anat_poi_PAC_RH', 'PT9_anat_poi_PAC_LH',
               'PT10_anat_poi_PAC_LH',
               'PT11_anat_poi_PAC_RH', 'PT11_anat_poi_PAC_LH',
               'PT12_anat_poi_PAC_RH', 'PT12_anat_poi_PAC_LH',
               'PT13_anat_poi_PAC_RH', 'PT13_anat_poi_PAC_LH',
               'PT14_anat_poi_PAC_LH',
               'PT15_anat_poi_PAC_RH', 'PT15_anat_poi_PAC_LH',
               'PT16_anat_poi_PAC_RH', 'PT16_anat_poi_PAC_LH',
               'PT17_anat_poi_PAC_RH', 'PT17_anat_poi_PAC_LH',
               'PT18_anat_poi_PAC_RH', 
               'PT19_anat_poi_PAC_LH',
               'PT20_anat_poi_PAC_RH', 'PT20_anat_poi_PAC_LH',
               'PT21_anat_poi_PAC_RH', 
               'PT22_anat_poi_PAC_RH',
               'PT23_anat_poi_PAC_LH',
               'PT24_anat_poi_PAC_RH']  
    # careful we're missing PT2LH,PT3LH,PT6RH,PT7RH,PT10RH,PT14RH,PT18LH,PT19RH,PT21LH,PT22LH,PT23RH,PT24LH

    ctl_dupl_full = ['CD','S', # right then left
                     'CD','S',
                     'PD','S',
                     'CD','S',
                     'S','S',
                     'CD','S',
                     'CD','S',
                     'PD','S',
                     'PD','CD',
                     'PD','S',
                     'CD','S',
                     'CD','CD'
                     ]

    pt_dupl_full = ['PD','S',
                    'PD',
                    'CD',
                    'CD','CD',
                    '?','S',
                    'S',
                    'CD',
                    'PD','S',
                    '?','PD',
                    'S',
                    'PD','S',
                    'PD','S',
                    'CD','?',
                    'CD',
                    'CD','PD',
                    'CD','?',
                    'S','S',
                    'PD',
                    'S',
                    '?','S',
                    'PD',
                    'PD',
                    'S',
                    'PD'
                    ]    

    
    ctl_list_relabelled = ['CTL1_tono_poi_PAC_RH',
                           'CTL2_tono_poi_PAC_LH',
                           'CTL2_tono_poi_PAC_RH',
                           'CTL3_tono_poi_PAC_LH',
                           'CTL3_tono_poi_PAC_RH',
                           'CTL4_tono_poi_PAC_RH',
                           'CTL5_tono_poi_PAC_RH',
                           'CTL6_tono_poi_PAC_LH',
                           'CTL6_tono_poi_PAC_RH',
                           'CTL8_tono_poi_PAC_LH',
                           'CTL8_tono_poi_PAC_RH',
                           'CTL9_tono_poi_PAC_LH',
                           'CTL9_tono_poi_PAC_RH',
                           'CTL10_tono_poi_PAC_RH',
                           'CTL12_tono_poi_PAC_LH',
                           'CTL12_tono_poi_PAC_RH',
                           'PT1_tono_poi_PAC_LH',
                           'PT1_tono_poi_PAC_RH',
                           'PT2_tono_poi_PAC_RH',
                           'PT3_tono_poi_PAC_RH',
                           'PT4_tono_poi_PAC_LH',
                           'PT4_tono_poi_PAC_RH',
                           'PT8_tono_poi_PAC_LH',
                           'PT8_tono_poi_PAC_RH',
                           'PT9_tono_poi_PAC_LH',
                           'PT9_tono_poi_PAC_RH',
                           'PT11_tono_poi_PAC_LH',
                           'PT13_tono_poi_PAC_RH',
                           'PT15_tono_poi_PAC_RH',
                           'PT20_tono_poi_PAC_RH',
                           'PT23_tono_poi_PAC_LH']
    
    ctl_anat_relabelled = ['CTL1_anat_poi_PAC_RH',
                           'CTL2_anat_poi_PAC_LH',
                           'CTL2_anat_poi_PAC_RH',
                           'CTL3_anat_poi_PAC_LH',
                           'CTL3_anat_poi_PAC_RH',
                           'CTL4_anat_poi_PAC_RH',
                           'CTL5_anat_poi_PAC_RH',
                           'CTL6_anat_poi_PAC_LH',
                           'CTL6_anat_poi_PAC_RH',
                           'CTL8_anat_poi_PAC_LH',
                           'CTL8_anat_poi_PAC_RH',
                           'CTL9_anat_poi_PAC_LH',
                           'CTL9_anat_poi_PAC_RH',
                           'CTL10_anat_poi_PAC_RH',
                           'CTL12_anat_poi_PAC_LH',
                           'CTL12_anat_poi_PAC_RH',
                           'PT1_anat_poi_PAC_LH',
                           'PT1_anat_poi_PAC_RH',
                           'PT2_anat_poi_PAC_RH',
                           'PT3_anat_poi_PAC_RH',
                           'PT4_anat_poi_PAC_LH',
                           'PT4_anat_poi_PAC_RH',
                           'PT8_anat_poi_PAC_LH',
                           'PT8_anat_poi_PAC_RH',
                           'PT9_anat_poi_PAC_LH',
                           'PT9_anat_poi_PAC_RH',
                           'PT11_anat_poi_PAC_LH',
                           'PT13_anat_poi_PAC_RH',
                           'PT15_anat_poi_PAC_RH',
                           'PT20_anat_poi_PAC_RH',
                           'PT23_anat_poi_PAC_LH']
    
    ctl_name_relabelled = ['Control re-1 (CTL1RH)',
                           'Control re-2 (CTL2LH)',
                           'Control re-3 (CTL2RH)',
                           'Control re-4 (CTL3LH)',
                           'Control re-5 (CTL3RH)',
                           'Control re-6 (CTL4RH)',
                           'Control re-7 (CTL5RH)',
                           'Control re-8 (CTL6LH)',
                           'Control re-9 (CTL6RH)',
                           'Control re-10 (CTL8LH)',
                           'Control re-11 (CTL8RH)',
                           'Control re-12 (CTL9LH)',
                           'Control re-13 (CTL9RH)',
                           'Control re-14 (CTL10RH)',
                           'Control re-15 (CTL12LH)',
                           'Control re-16 (CTL12RH)',
                           'Control re-17 (PT1LH)',
                           'Control re-18 (PT1RH)',
                           'Control re-19 (PT2RH)',
                           'Control re-20 (PT3RH)',
                           'Control re-21 (PT4LH)',
                           'Control re-22 (PT4RH)',
                           'Control re-23 (PT8LH)',
                           'Control re-24 (PT8RH)',
                           'Control re-25 (PT9LH)',
                           'Control re-26 (PT9RH)',
                           'Control re-27 (PT11LH)',
                           'Control re-28 (PT13RH)',
                           'Control re-29 (PT15RH)',
                           'Control re-30 (PT20RH)',
                           'Control re-31 (PT23LH)'
                            ]
    
    pt_list_relabelled = ['CTL1_tono_poi_PAC_LH',
                          'CTL4_tono_poi_PAC_LH',
                          'CTL5_tono_poi_PAC_LH',
                          'CTL7_tono_poi_PAC_LH',
                          'CTL7_tono_poi_PAC_RH',
                          'CTL10_tono_poi_PAC_LH',
                          'PT5_tono_poi_PAC_LH',
                          'PT5_tono_poi_PAC_RH',
                          'PT6_tono_poi_PAC_LH',
                          'PT7_tono_poi_PAC_LH',
                          'PT10_tono_poi_PAC_LH',
                          'PT11_tono_poi_PAC_RH',
                          'PT12_tono_poi_PAC_LH',
                          'PT12_tono_poi_PAC_RH',
                          'PT13_tono_poi_PAC_LH',
                          'PT14_tono_poi_PAC_LH',
                          'PT15_tono_poi_PAC_LH',
                          'PT16_tono_poi_PAC_LH',
                          'PT16_tono_poi_PAC_RH',
                          'PT17_tono_poi_PAC_LH',
                          'PT17_tono_poi_PAC_RH',
                          'PT18_tono_poi_PAC_RH',
                          'PT19_tono_poi_PAC_LH',
                          'PT20_tono_poi_PAC_LH',
                          'PT21_tono_poi_PAC_RH',
                          'PT22_tono_poi_PAC_RH',
                          'PT24_tono_poi_PAC_RH'
                          ]
    
    pt_anat_relabelled = ['CTL1_anat_poi_PAC_LH',
                          'CTL4_anat_poi_PAC_LH',
                          'CTL5_anat_poi_PAC_LH',
                          'CTL7_anat_poi_PAC_LH',
                          'CTL7_anat_poi_PAC_RH',
                          'CTL10_anat_poi_PAC_LH',
                          'PT5_anat_poi_PAC_LH',
                          'PT5_anat_poi_PAC_RH',
                          'PT6_anat_poi_PAC_LH',
                          'PT7_anat_poi_PAC_LH',
                          'PT10_anat_poi_PAC_LH',
                          'PT11_anat_poi_PAC_RH',
                          'PT12_anat_poi_PAC_LH',
                          'PT12_anat_poi_PAC_RH',
                          'PT13_anat_poi_PAC_LH',
                          'PT14_anat_poi_PAC_LH',
                          'PT15_anat_poi_PAC_LH',
                          'PT16_anat_poi_PAC_LH',
                          'PT16_anat_poi_PAC_RH',
                          'PT17_anat_poi_PAC_LH',
                          'PT17_anat_poi_PAC_RH',
                          'PT18_anat_poi_PAC_RH',
                          'PT19_anat_poi_PAC_LH',
                          'PT20_anat_poi_PAC_LH',
                          'PT21_anat_poi_PAC_RH',
                          'PT22_anat_poi_PAC_RH',
                          'PT24_anat_poi_PAC_RH'
                          ]
    
    
    pt_name_relabelled = ['Patient re-1 (CTL1LH)',
                          'Patient re-2 (CTL4LH)',
                          'Patient re-3 (CTL5LH)',
                          'Patient re-4 (CTL7LH)',
                          'Patient re-5 (CTL7RH)',
                          'Patient re-6 (CTL10LH)',
                          'Patient re-7 (PT5LH)',
                          'Patient re-8 (PT5RH)',
                          'Patient re-9 (PT6LH)',
                          'Patient re-10 (PT7LH)',
                          'Patient re-11 (PT10RH)',
                          'Patient re-12 (PT11RH)',
                          'Patient re-13 (PT12LH)',
                          'Patient re-14 (PT12RH)',
                          'Patient re-15 (PT13LH)',
                          'Patient re-16 (PT14LH)',
                          'Patient re-17 (PT15LH)',
                          'Patient re-18 (PT16LH)',
                          'Patient re-19 (PT16RH)',
                          'Patient re-20 (PT17LH)',
                          'Patient re-21 (PT17RH)',
                          'Patient re-22 (PT18RH)',
                          'Patient re-23 (PT19LH)',
                          'Patient re-24 (PT20LH)',
                          'Patient re-25 (PT21RH)',
                          'Patient re-26 (PT22RH)',
                          'Patient re-27 (PT24RH)'
                          ]
    
    ctl_dupl_relab = ['CD',
                      'S',
                      'CD',
                      'S',
                      'PD',
                      'CD',
                      'S',
                      'S',
                      'CD',
                      'S',
                      'PD',
                      'CD',
                      'PD',
                      'PD',
                      'S',
                      'CD',
                      'S',
                      'PD',
                      'PD',
                      'CD',
                      'CD',
                      'CD',
                      'S',
                      'PD',
                      'PD',
                      'CD',
                      'S',
                      'S',
                      'CD',
                      'CD',
                      'S']
    pt_dupl_relab = ['S',
                     'S',
                     'S',
                     'S',
                     'CD',
                     'S',
                     'S',
                     'PD',
                     'S',
                     'CD',
                     'CD',
                     'PD',
                     'S',
                     'PD',
                     'CD',
                     'CD',
                     'PD',
                     'CD',
                     'CD',
                     'S',
                     'S',
                     'PD',
                     'S',
                     'S',
                     'PD',
                     'PD',
                     'PD']  
    
    # labels are 0 for controls and 1 for patients
    
    if which_dataset == 'normalized':
        data_tono = np.concatenate((ctl_list_norm, pt_list_norm))
        data_anat = []
        data_dupl = []
        data_names = np.concatenate((ctl_name_norm, pt_name_norm))
        targets = np.concatenate((np.zeros(len(ctl_list_norm)),np.ones(pt_list_norm)))
        
    elif which_dataset == 'full':
        data_tono = np.concatenate((ctl_list_full, pt_list_full))
        data_anat = np.concatenate((ctl_anat_full, pt_anat_full))
        data_dupl = np.concatenate((ctl_dupl_full,pt_dupl_full))
        data_names = np.concatenate((ctl_name_full, pt_name_full))
        targets = np.concatenate((np.zeros(len(ctl_list_full)),np.ones(pt_list_full)))
        
    elif which_dataset == 'relabelled':
        data_tono = np.concatenate((ctl_list_relabelled, pt_list_relabelled))
        data_anat = np.concatenate((ctl_anat_relabelled, pt_anat_relabelled))
        data_dupl = np.concatenate((ctl_dupl_relab,pt_dupl_relab))
        data_names = np.concatenate((ctl_name_relabelled, pt_name_relabelled))
        targets = np.concatenate((np.zeros(len(ctl_list_relabelled)),np.ones(pt_list_relabelled)))
        
    return data_tono, data_anat, data_dupl, data_names, targets