# -*- coding: utf-8 -*-
"""
Created on Tue Nov 13 22:32:47 2018

@author: Giorgia
"""
import numpy as np

# This script contains a function that returns a list with the name of the files and the corresponding labels
def define_data_and_labels(which_dataset):
    ctl_list_norm = ['CTL1_tono_voi_onRef_PAC_RH.txt','CTL1_tono_voi_onRef_PAC_LH.txt',
                 'CTL2_tono_voi_onRef_PAC_RH.txt','CTL2_tono_voi_onRef_PAC_LH.txt',
                 'CTL3_tono_voi_onRef_PAC_RH.txt','CTL3_tono_voi_onRef_PAC_LH.txt',
                 'CTL4_tono_voi_onRef_PAC_RH.txt','CTL4_tono_voi_onRef_PAC_LH.txt',
                 'CTL5_tono_voi_onRef_PAC_RH.txt','CTL5_tono_voi_onRef_PAC_LH.txt',
                 'CTL6_tono_voi_onRef_PAC_RH.txt','CTL6_tono_voi_onRef_PAC_LH.txt',
                 'CTL7_tono_voi_onRef_PAC_RH.txt','CTL7_tono_voi_onRef_PAC_LH.txt',
                 'CTL8_tono_voi_onRef_PAC_RH.txt','CTL8_tono_voi_onRef_PAC_LH.txt',
                 'CTL9_tono_voi_onRef_PAC_RH.txt','CTL9_tono_voi_onRef_PAC_LH.txt',
                 'CTL10_tono_voi_onRef_PAC_RH.txt','CTL10_tono_voi_onRef_PAC_LH.txt',
                 'CTL12_tono_voi_onRef_PAC_RH.txt','CTL12_tono_voi_onRef_PAC_LH.txt',
                 'CTL13_tono_voi_onRef_PAC_RH.txt','CTL13_tono_voi_onRef_PAC_LH.txt']

    pt_list_norm = ['PT1_tono_voi_onRef_PAC_RH.txt','PT1_tono_voi_onRef_PAC_LH.txt',
               'PT2_tono_voi_onRef_PAC_RH.txt','PT2_tono_voi_onRef_PAC_LH.txt',
               'PT3_tono_voi_onRef_PAC_RH.txt','PT3_tono_voi_onRef_PAC_LH.txt',
               'PT4_tono_voi_onRef_PAC_RH.txt','PT4_tono_voi_onRef_PAC_LH.txt',
               'PT5_tono_voi_onRef_PAC_RH.txt','PT5_tono_voi_onRef_PAC_LH.txt',
               'PT6_tono_voi_onRef_PAC_RH.txt','PT6_tono_voi_onRef_PAC_LH.txt',
               'PT7_tono_voi_onRef_PAC_RH.txt','PT7_tono_voi_onRef_PAC_LH.txt',
               'PT8_tono_voi_onRef_PAC_RH.txt','PT8_tono_voi_onRef_PAC_LH.txt',
               'PT9_tono_voi_onRef_PAC_RH.txt','PT9_tono_voi_onRef_PAC_LH.txt',
               'PT10_tono_voi_onRef_PAC_RH.txt','PT10_tono_voi_onRef_PAC_LH.txt',
               'PT11_tono_voi_onRef_PAC_RH.txt','PT11_tono_voi_onRef_PAC_LH.txt',
               'PT12_tono_voi_onRef_PAC_RH.txt','PT12_tono_voi_onRef_PAC_LH.txt',
               'PT13_tono_voi_onRef_PAC_RH.txt','PT13_tono_voi_onRef_PAC_LH.txt',
               'PT14_tono_voi_onRef_PAC_RH.txt','PT14_tono_voi_onRef_PAC_LH.txt',
               'PT15_tono_voi_onRef_PAC_RH.txt','PT15_tono_voi_onRef_PAC_LH.txt',
               'PT16_tono_voi_onRef_PAC_RH.txt','PT16_tono_voi_onRef_PAC_LH.txt',
               'PT17_tono_voi_onRef_PAC_RH.txt','PT17_tono_voi_onRef_PAC_LH.txt',
               'PT18_tono_voi_onRef_PAC_RH.txt','PT18_tono_voi_onRef_PAC_LH.txt',
               'PT19_tono_voi_onRef_PAC_RH.txt','PT19_tono_voi_onRef_PAC_LH.txt',
               'PT20_tono_voi_onRef_PAC_RH.txt','PT20_tono_voi_onRef_PAC_LH.txt',
               'PT21_tono_voi_onRef_PAC_RH.txt','PT21_tono_voi_onRef_PAC_LH.txt',
               'PT22_tono_voi_onRef_PAC_RH.txt','PT22_tono_voi_onRef_PAC_LH.txt',
               'PT23_tono_voi_onRef_PAC_RH.txt','PT23_tono_voi_onRef_PAC_LH.txt',
               'PT24_tono_voi_onRef_PAC_RH.txt','PT24_tono_voi_onRef_PAC_LH.txt']
    ctl_name_norm = ['Control 1 - RH','Control 1 - LH',
                'Control 2 - RH','Control 2 - LH',
                'Control 3 - RH','Control 3 - LH',
                'Control 4 - RH','Control 4 - LH',
                'Control 5 - RH','Control 5 - LH',
                'Control 6 - RH','Control 6 - LH',
                'Control 7 - RH','Control 7 - LH',
                'Control 8 - RH','Control 8 - LH',
                'Control 9 - RH','Control 9 - LH',
                'Control 10 - RH','Control 10 - LH',
                'Control 12 - RH','Control 12 - LH',
                'Control 13 - RH','Control 13 - LH']
    
    pt_name_norm = ['Patient 1 - RH', 'Patient 1 - LH',
               'Patient 2 - RH', 'Patient 2 - LH',
               'Patient 3 - RH', 'Patient 3 - LH',
               'Patient 4 - RH', 'Patient 4 - LH',
               'Patient 5 - RH', 'Patient 5 - LH',
               'Patient 6 - RH', 'Patient 6 - LH',
               'Patient 7 - RH', 'Patient 7 - LH',
               'Patient 8 - RH', 'Patient 8 - LH',
               'Patient 9 - RH', 'Patient 9 - LH',
               'Patient 10 - RH', 'Patient 10 - LH',
               'Patient 11 - RH', 'Patient 11 - LH',
               'Patient 12 - RH', 'Patient 12 - LH',
               'Patient 13 - RH', 'Patient 13 - LH',
               'Patient 14 - RH', 'Patient 14 - LH',
               'Patient 15 - RH', 'Patient 15 - LH',
               'Patient 16 - RH', 'Patient 16 - LH',
               'Patient 17 - RH', 'Patient 17 - LH',
               'Patient 18 - RH', 'Patient 18 - LH',
               'Patient 19 - RH', 'Patient 19 - LH',
               'Patient 20 - RH', 'Patient 20 - LH',
               'Patient 21 - RH', 'Patient 21 - LH',
               'Patient 22 - RH', 'Patient 22 - LH',
               'Patient 23 - RH', 'Patient 23 - LH',
               'Patient 24 - RH', 'Patient 24 - LH']
    
    ctl_list_full = ['CTL1_tono_poi_PAC_RH', 'CTL1_tono_poi_PAC_LH',
                     'CTL2_tono_poi_PAC_RH', 'CTL2_tono_poi_PAC_LH',
                     'CTL3_tono_poi_PAC_RH', 'CTL3_tono_poi_PAC_LH',
                     'CTL4_tono_poi_PAC_RH', 'CTL4_tono_poi_PAC_LH',
                     'CTL5_tono_poi_PAC_RH', 'CTL5_tono_poi_PAC_LH',
                     'CTL6_tono_poi_PAC_RH', 'CTL6_tono_poi_PAC_LH',
                     'CTL7_tono_poi_PAC_RH', 'CTL7_tono_poi_PAC_LH',
                     'CTL8_tono_poi_PAC_RH', 'CTL8_tono_poi_PAC_LH',
                     'CTL9_tono_poi_PAC_RH', 'CTL9_tono_poi_PAC_LH',
                     'CTL10_tono_poi_PAC_RH', 'CTL10_tono_poi_PAC_LH',
                     'CTL12_tono_poi_PAC_RH', 'CTL12_tono_poi_PAC_LH']
    
    pt_list_full = ['PT1_tono_poi_PAC_RH', 'PT1_tono_poi_PAC_LH',
                    'PT2_tono_poi_PAC_RH', 
                    'PT3_tono_poi_PAC_RH',
                    'PT4_tono_poi_PAC_RH', 'PT4_tono_poi_PAC_LH',
                    'PT5_tono_poi_PAC_RH', 'PT5_tono_poi_PAC_LH',
                    'PT6_tono_poi_PAC_LH',
                    'PT7_tono_poi_PAC_LH',
                    'PT8_tono_poi_PAC_RH', 'PT8_tono_poi_PAC_LH',
                    'PT9_tono_poi_PAC_RH', 'PT9_tono_poi_PAC_LH',
                    'PT10_tono_poi_PAC_LH',
                    'PT11_tono_poi_PAC_RH', 'PT11_tono_poi_PAC_LH',
                    'PT12_tono_poi_PAC_RH', 'PT12_tono_poi_PAC_LH',
                    'PT13_tono_poi_PAC_RH', 'PT13_tono_poi_PAC_LH',
                    'PT14_tono_poi_PAC_LH',
                    'PT15_tono_poi_PAC_RH', 'PT15_tono_poi_PAC_LH',
                    'PT16_tono_poi_PAC_RH', 'PT16_tono_poi_PAC_LH',
                    'PT17_tono_poi_PAC_RH', 'PT17_tono_poi_PAC_LH',
                    'PT18_tono_poi_PAC_RH',
                    'PT19_tono_poi_PAC_LH',
                    'PT20_tono_poi_PAC_RH', 'PT20_tono_poi_PAC_LH',
                    'PT21_tono_poi_PAC_RH',
                    'PT22_tono_poi_PAC_RH',
                    'PT23_tono_poi_PAC_LH',
                    'PT24_tono_poi_PAC_RH'] # careful we're missing PT2LH,PT3LH,PT6RH,PT7RH,PT10RH,PT14RH,PT18LH,PT19RH,PT21LH,PT22LH,PT23RH,PT24LH

    ctl_name_full = ['Control 1 - RH','Control 1 - LH',
                'Control 2 - RH','Control 2 - LH',
                'Control 3 - RH','Control 3 - LH',
                'Control 4 - RH','Control 4 - LH',
                'Control 5 - RH','Control 5 - LH',
                'Control 6 - RH','Control 6 - LH',
                'Control 7 - RH','Control 7 - LH',
                'Control 8 - RH','Control 8 - LH',
                'Control 9 - RH','Control 9 - LH',
                'Control 10 - RH','Control 10 - LH',
                'Control 12 - RH','Control 12 - LH',
                'Control 13 - RH','Control 13 - LH']
    
    pt_name_full = ['Patient 1 - RH', 'Patient 1 - LH',
               'Patient 2 - RH', 
               'Patient 3 - RH', 
               'Patient 4 - RH', 'Patient 4 - LH',
               'Patient 5 - RH', 'Patient 5 - LH',
               'Patient 6 - LH',
               'Patient 7 - LH',
               'Patient 8 - RH', 'Patient 8 - LH',
               'Patient 9 - RH', 'Patient 9 - LH',
               'Patient 10 - LH',
               'Patient 11 - RH', 'Patient 11 - LH',
               'Patient 12 - RH', 'Patient 12 - LH',
               'Patient 13 - RH', 'Patient 13 - LH',
               'Patient 14 - LH',
               'Patient 15 - RH', 'Patient 15 - LH',
               'Patient 16 - RH', 'Patient 16 - LH',
               'Patient 17 - RH', 'Patient 17 - LH',
               'Patient 18 - RH',
               'Patient 19 - LH',
               'Patient 20 - RH', 'Patient 20 - LH',
               'Patient 21 - RH',
               'Patient 22 - RH',
               'Patient 23 - LH',
               'Patient 24 - RH']

    
    ctl_anat_full = ['CTL1_anat_poi_PAC_RH', 'CTL1_anat_poi_PAC_LH',
                'CTL2_anat_poi_PAC_RH', 'CTL2_anat_poi_PAC_LH',
                'CTL3_anat_poi_PAC_RH', 'CTL3_anat_poi_PAC_LH',
                'CTL4_anat_poi_PAC_RH', 'CTL4_anat_poi_PAC_LH',
                'CTL5_anat_poi_PAC_RH', 'CTL5_anat_poi_PAC_LH',
                'CTL6_anat_poi_PAC_RH', 'CTL6_anat_poi_PAC_LH',
                'CTL7_anat_poi_PAC_RH', 'CTL7_anat_poi_PAC_LH',
                'CTL8_anat_poi_PAC_RH', 'CTL8_anat_poi_PAC_LH',
                'CTL9_anat_poi_PAC_RH', 'CTL9_anat_poi_PAC_LH',
                'CTL10_anat_poi_PAC_RH', 'CTL10_anat_poi_PAC_LH',
                'CTL12_anat_poi_PAC_RH', 'CTL12_anat_poi_PAC_LH']

    pt_anat_full = ['PT1_anat_poi_PAC_RH', 'PT1_anat_poi_PAC_LH',
               'PT2_anat_poi_PAC_RH', 
               'PT3_anat_poi_PAC_RH',
               'PT4_anat_poi_PAC_RH', 'PT4_anat_poi_PAC_LH',
               'PT5_anat_poi_PAC_RH', 'PT5_anat_poi_PAC_LH',
               'PT6_anat_poi_PAC_LH',
               'PT7_anat_poi_PAC_LH',
               'PT8_anat_poi_PAC_RH', 'PT8_anat_poi_PAC_LH',
               'PT9_anat_poi_PAC_RH', 'PT9_anat_poi_PAC_LH',
               'PT10_anat_poi_PAC_LH',
               'PT11_anat_poi_PAC_RH', 'PT11_anat_poi_PAC_LH',
               'PT12_anat_poi_PAC_RH', 'PT12_anat_poi_PAC_LH',
               'PT13_anat_poi_PAC_RH', 'PT13_anat_poi_PAC_LH',
               'PT14_anat_poi_PAC_LH',
               'PT15_anat_poi_PAC_RH', 'PT15_anat_poi_PAC_LH',
               'PT16_anat_poi_PAC_RH', 'PT16_anat_poi_PAC_LH',
               'PT17_anat_poi_PAC_RH', 'PT17_anat_poi_PAC_LH',
               'PT18_anat_poi_PAC_RH', 
               'PT19_anat_poi_PAC_LH',
               'PT20_anat_poi_PAC_RH', 'PT20_anat_poi_PAC_LH',
               'PT21_anat_poi_PAC_RH', 
               'PT22_anat_poi_PAC_RH',
               'PT23_anat_poi_PAC_LH',
               'PT24_anat_poi_PAC_RH']  
    # careful we're missing PT2LH,PT3LH,PT6RH,PT7RH,PT10RH,PT14RH,PT18LH,PT19RH,PT21LH,PT22LH,PT23RH,PT24LH

    ctl_dupl_full = ['CD','S', # right then left
                     'CD','S',
                     'PD','S',
                     'CD','S',
                     'S','S',
                     'CD','S',
                     'CD','S',
                     'PD','S',
                     'PD','CD',
                     'PD','S',
                     'CD','S',
                     'CD','CD'
                     ]

    pt_dupl_full = ['PD','S',
                    'PD',
                    'CD',
                    'CD','CD',
                    '?','S',
                    'S',
                    'CD',
                    'PD','S',
                    '?','PD',
                    'S',
                    'PD','S',
                    'PD','S',
                    'CD','?',
                    'CD',
                    'CD','PD',
                    'CD','?',
                    'S','S',
                    'PD',
                    'S',
                    '?','S',
                    'PD',
                    'PD',
                    'S',
                    'PD'
                    ]    

    
    ctl_list_relabelled = ['CTL1_tono_poi_PAC_RH',
                           'CTL2_tono_poi_PAC_LH',
                           'CTL2_tono_poi_PAC_RH',
                           'CTL3_tono_poi_PAC_LH',
                           'CTL3_tono_poi_PAC_RH',
                           'CTL4_tono_poi_PAC_RH',
                           'CTL5_tono_poi_PAC_RH',
                           'CTL6_tono_poi_PAC_LH',
                           'CTL6_tono_poi_PAC_RH',
                           'CTL8_tono_poi_PAC_LH',
                           'CTL8_tono_poi_PAC_RH',
                           'CTL9_tono_poi_PAC_LH',
                           'CTL9_tono_poi_PAC_RH',
                           'CTL10_tono_poi_PAC_RH',
                           'CTL12_tono_poi_PAC_LH',
                           'CTL12_tono_poi_PAC_RH',
                           'PT1_tono_poi_PAC_LH',
                           'PT1_tono_poi_PAC_RH',
                           'PT2_tono_poi_PAC_RH',
                           'PT3_tono_poi_PAC_RH',
                           'PT4_tono_poi_PAC_LH',
                           'PT4_tono_poi_PAC_RH',
                           'PT8_tono_poi_PAC_LH',
                           'PT8_tono_poi_PAC_RH',
                           'PT9_tono_poi_PAC_LH',
                           'PT9_tono_poi_PAC_RH',
                           'PT11_tono_poi_PAC_LH',
                           'PT13_tono_poi_PAC_RH',
                           'PT15_tono_poi_PAC_RH',
                           'PT20_tono_poi_PAC_RH',
                           'PT23_tono_poi_PAC_LH']
    
    ctl_anat_relabelled = ['CTL1_anat_poi_PAC_RH',
                           'CTL2_anat_poi_PAC_LH',
                           'CTL2_anat_poi_PAC_RH',
                           'CTL3_anat_poi_PAC_LH',
                           'CTL3_anat_poi_PAC_RH',
                           'CTL4_anat_poi_PAC_RH',
                           'CTL5_anat_poi_PAC_RH',
                           'CTL6_anat_poi_PAC_LH',
                           'CTL6_anat_poi_PAC_RH',
                           'CTL8_anat_poi_PAC_LH',
                           'CTL8_anat_poi_PAC_RH',
                           'CTL9_anat_poi_PAC_LH',
                           'CTL9_anat_poi_PAC_RH',
                           'CTL10_anat_poi_PAC_RH',
                           'CTL12_anat_poi_PAC_LH',
                           'CTL12_anat_poi_PAC_RH',
                           'PT1_anat_poi_PAC_LH',
                           'PT1_anat_poi_PAC_RH',
                           'PT2_anat_poi_PAC_RH',
                           'PT3_anat_poi_PAC_RH',
                           'PT4_anat_poi_PAC_LH',
                           'PT4_anat_poi_PAC_RH',
                           'PT8_anat_poi_PAC_LH',
                           'PT8_anat_poi_PAC_RH',
                           'PT9_anat_poi_PAC_LH',
                           'PT9_anat_poi_PAC_RH',
                           'PT11_anat_poi_PAC_LH',
                           'PT13_anat_poi_PAC_RH',
                           'PT15_anat_poi_PAC_RH',
                           'PT20_anat_poi_PAC_RH',
                           'PT23_anat_poi_PAC_LH']
    
    ctl_name_relabelled = ['Control re-1 (CTL1RH)',
                           'Control re-2 (CTL2LH)',
                           'Control re-3 (CTL2RH)',
                           'Control re-4 (CTL3LH)',
                           'Control re-5 (CTL3RH)',
                           'Control re-6 (CTL4RH)',
                           'Control re-7 (CTL5RH)',
                           'Control re-8 (CTL6LH)',
                           'Control re-9 (CTL6RH)',
                           'Control re-10 (CTL8LH)',
                           'Control re-11 (CTL8RH)',
                           'Control re-12 (CTL9LH)',
                           'Control re-13 (CTL9RH)',
                           'Control re-14 (CTL10RH)',
                           'Control re-15 (CTL12LH)',
                           'Control re-16 (CTL12RH)',
                           'Control re-17 (PT1LH)',
                           'Control re-18 (PT1RH)',
                           'Control re-19 (PT2RH)',
                           'Control re-20 (PT3RH)',
                           'Control re-21 (PT4LH)',
                           'Control re-22 (PT4RH)',
                           'Control re-23 (PT8LH)',
                           'Control re-24 (PT8RH)',
                           'Control re-25 (PT9LH)',
                           'Control re-26 (PT9RH)',
                           'Control re-27 (PT11LH)',
                           'Control re-28 (PT13RH)',
                           'Control re-29 (PT15RH)',
                           'Control re-30 (PT20RH)',
                           'Control re-31 (PT23LH)'
                            ]
    
    pt_list_relabelled = ['CTL1_tono_poi_PAC_LH',
                          'CTL4_tono_poi_PAC_LH',
                          'CTL5_tono_poi_PAC_LH',
                          'CTL7_tono_poi_PAC_LH',
                          'CTL7_tono_poi_PAC_RH',
                          'CTL10_tono_poi_PAC_LH',
                          'PT5_tono_poi_PAC_LH',
                          'PT5_tono_poi_PAC_RH',
                          'PT6_tono_poi_PAC_LH',
                          'PT7_tono_poi_PAC_LH',
                          'PT10_tono_poi_PAC_LH',
                          'PT11_tono_poi_PAC_RH',
                          'PT12_tono_poi_PAC_LH',
                          'PT12_tono_poi_PAC_RH',
                          'PT13_tono_poi_PAC_LH',
                          'PT14_tono_poi_PAC_LH',
                          'PT15_tono_poi_PAC_LH',
                          'PT16_tono_poi_PAC_LH',
                          'PT16_tono_poi_PAC_RH',
                          'PT17_tono_poi_PAC_LH',
                          'PT17_tono_poi_PAC_RH',
                          'PT18_tono_poi_PAC_RH',
                          'PT19_tono_poi_PAC_LH',
                          'PT20_tono_poi_PAC_LH',
                          'PT21_tono_poi_PAC_RH',
                          'PT22_tono_poi_PAC_RH',
                          'PT24_tono_poi_PAC_RH'
                          ]
    
    pt_anat_relabelled = ['CTL1_anat_poi_PAC_LH',
                          'CTL4_anat_poi_PAC_LH',
                          'CTL5_anat_poi_PAC_LH',
                          'CTL7_anat_poi_PAC_LH',
                          'CTL7_anat_poi_PAC_RH',
                          'CTL10_anat_poi_PAC_LH',
                          'PT5_anat_poi_PAC_LH',
                          'PT5_anat_poi_PAC_RH',
                          'PT6_anat_poi_PAC_LH',
                          'PT7_anat_poi_PAC_LH',
                          'PT10_anat_poi_PAC_LH',
                          'PT11_anat_poi_PAC_RH',
                          'PT12_anat_poi_PAC_LH',
                          'PT12_anat_poi_PAC_RH',
                          'PT13_anat_poi_PAC_LH',
                          'PT14_anat_poi_PAC_LH',
                          'PT15_anat_poi_PAC_LH',
                          'PT16_anat_poi_PAC_LH',
                          'PT16_anat_poi_PAC_RH',
                          'PT17_anat_poi_PAC_LH',
                          'PT17_anat_poi_PAC_RH',
                          'PT18_anat_poi_PAC_RH',
                          'PT19_anat_poi_PAC_LH',
                          'PT20_anat_poi_PAC_LH',
                          'PT21_anat_poi_PAC_RH',
                          'PT22_anat_poi_PAC_RH',
                          'PT24_anat_poi_PAC_RH'
                          ]
    pt_name_relabelled = ['Patient re-1 (CTL1LH)',
                          'Patient re-2 (CTL4LH)',
                          'Patient re-3 (CTL5LH)',
                          'Patient re-4 (CTL7LH)',
                          'Patient re-5 (CTL7RH)',
                          'Patient re-6 (CTL10LH)',
                          'Patient re-7 (PT5LH)',
                          'Patient re-8 (PT5RH)',
                          'Patient re-9 (PT6LH)',
                          'Patient re-10 (PT7LH)',
                          'Patient re-11 (PT10RH)',
                          'Patient re-12 (PT11RH)',
                          'Patient re-13 (PT12LH)',
                          'Patient re-14 (PT12RH)',
                          'Patient re-15 (PT13LH)',
                          'Patient re-16 (PT14LH)',
                          'Patient re-17 (PT15LH)',
                          'Patient re-18 (PT16LH)',
                          'Patient re-19 (PT16RH)',
                          'Patient re-20 (PT17LH)',
                          'Patient re-21 (PT17RH)',
                          'Patient re-22 (PT18RH)',
                          'Patient re-23 (PT19LH)',
                          'Patient re-24 (PT20LH)',
                          'Patient re-25 (PT21RH)',
                          'Patient re-26 (PT22RH)',
                          'Patient re-27 (PT24RH)']
    ctl_dupl_relab = ['CD',
                      'S',
                      'CD',
                      'S',
                      'PD',
                      'CD',
                      'S',
                      'S',
                      'CD',
                      'S',
                      'PD',
                      'CD',
                      'PD',
                      'PD',
                      'S',
                      'CD',
                      'S',
                      'PD',
                      'PD',
                      'CD',
                      'CD',
                      'CD',
                      'S',
                      'PD',
                      'PD',
                      'CD',
                      'S',
                      'S',
                      'CD',
                      'CD',
                      'S']
    pt_dupl_relab = ['S',
                     'S',
                     'S',
                     'S',
                     'CD',
                     'S',
                     'S',
                     'PD',
                     'S',
                     'CD',
                     'CD',
                     'PD',
                     'S',
                     'PD',
                     'CD',
                     'CD',
                     'PD',
                     'CD',
                     'CD',
                     'S',
                     'S',
                     'PD',
                     'S',
                     'S',
                     'PD',
                     'PD',
                     'PD']  
    big_dataset_tono = ['C1_tono_poi_STG_LH.txt','C1_tono_poi_STG_RH.txt',
                        'C2_tono_poi_STG_LH.txt','C2_tono_poi_STG_RH.txt',
                        'C3_tono_poi_STG_LH.txt','C3_tono_poi_STG_RH.txt',
                        'C4_tono_poi_STG_LH.txt','C4_tono_poi_STG_RH.txt',
                        'C5_tono_poi_STG_LH.txt','C5_tono_poi_STG_RH.txt',
                        'C6_tono_poi_STG_LH.txt','C6_tono_poi_STG_RH.txt',
                        'C7_tono_poi_STG_LH.txt','C7_tono_poi_STG_RH.txt',
                        'C8_tono_poi_STG_LH.txt','C8_tono_poi_STG_RH.txt',
                        'C9_tono_poi_STG_LH.txt','C9_tono_poi_STG_RH.txt',
                        'C10_tono_poi_STG_LH.txt','C10_tono_poi_STG_RH.txt',
                        'C11_tono_poi_STG_LH.txt','C11_tono_poi_STG_RH.txt',
                        'C12_tono_poi_STG_LH.txt','C12_tono_poi_STG_RH.txt',
                        'C13_tono_poi_STG_LH.txt','C13_tono_poi_STG_RH.txt',
                        'C14_tono_poi_STG_LH.txt','C14_tono_poi_STG_RH.txt',
                        'C15_tono_poi_STG_LH.txt',
                        'C16_tono_poi_STG_LH.txt',
                        
                        'C18_tono_poi_STG_LH.txt','C18_tono_poi_STG_RH.txt',
                        'C19_tono_poi_STG_LH.txt','C19_tono_poi_STG_RH.txt',
                        'C20_tono_poi_STG_LH.txt','C20_tono_poi_STG_RH.txt',
                        'C21_tono_poi_STG_LH.txt','C21_tono_poi_STG_RH.txt',
                        'C22_tono_poi_STG_LH.txt','C22_tono_poi_STG_RH.txt',
                        'C23_tono_poi_STG_LH.txt','C23_tono_poi_STG_RH.txt',
                        
                        'C25_tono_poi_STG_LH.txt','C25_tono_poi_STG_RH.txt',
                        'C26_tono_poi_STG_LH.txt','C26_tono_poi_STG_RH.txt',
                        'C27_tono_poi_STG_LH.txt','C27_tono_poi_STG_RH.txt',
                        'C28_tono_poi_STG_LH.txt','C28_tono_poi_STG_RH.txt',
                        'C29_tono_poi_STG_RH.txt',
                        'C30_tono_poi_STG_LH.txt',
                        'C31_tono_poi_STG_RH.txt',
                        'C32_tono_poi_STG_LH.txt','C32_tono_poi_STG_RH.txt',
                        'C33_tono_poi_STG_LH.txt','C33_tono_poi_STG_RH.txt',
                        'C34_tono_poi_STG_RH.txt',
                        'C35_tono_poi_STG_RH.txt',
                        'C36_tono_poi_STG_LH.txt',
                        
                        'C38_tono_poi_STG_RH.txt',
                        
                        'C40_tono_poi_STG_RH.txt',
                        'C41_tono_poi_STG_LH.txt','C41_tono_poi_STG_RH.txt',
                        'C42_tono_poi_STG_LH.txt','C42_tono_poi_STG_RH.txt',
                        'C43_tono_poi_STG_LH.txt','C43_tono_poi_STG_RH.txt',
                        'C44_tono_poi_STG_LH.txt','C44_tono_poi_STG_RH.txt',
                        'C45_tono_poi_STG_LH.txt','C45_tono_poi_STG_RH.txt',
                        'C46_tono_poi_STG_LH.txt','C46_tono_poi_STG_RH.txt',
                        'C47_tono_poi_STG_LH.txt','C47_tono_poi_STG_RH.txt',
                        'C48_tono_poi_STG_LH.txt','C48_tono_poi_STG_RH.txt',
                        'C49_tono_poi_STG_LH.txt','C49_tono_poi_STG_RH.txt',
                        'C50_tono_poi_STG_LH.txt','C50_tono_poi_STG_RH.txt',
                        'C51_tono_poi_STG_LH.txt','C51_tono_poi_STG_RH.txt',
                        'C52_tono_poi_STG_LH.txt','C52_tono_poi_STG_RH.txt',
                        'C53_tono_poi_STG_LH.txt','C53_tono_poi_STG_RH.txt',
                        'C54_tono_poi_STG_LH.txt','C54_tono_poi_STG_RH.txt',
                        'C55_tono_poi_STG_LH.txt','C55_tono_poi_STG_RH.txt',
                        'C56_tono_poi_STG_LH.txt','C56_tono_poi_STG_RH.txt',
                        'C57_tono_poi_STG_LH.txt','C57_tono_poi_STG_RH.txt',
                        'C58_tono_poi_STG_LH.txt','C58_tono_poi_STG_RH.txt',
                        'C59_tono_poi_STG_LH.txt','C59_tono_poi_STG_RH.txt',
                        'C60_tono_poi_STG_LH.txt','C60_tono_poi_STG_RH.txt',
                        'C61_tono_poi_STG_LH.txt','C61_tono_poi_STG_RH.txt',
                        'C62_tono_poi_STG_LH.txt','C62_tono_poi_STG_RH.txt',
                        'C63_tono_poi_STG_LH.txt','C63_tono_poi_STG_RH.txt',
                        'C64_tono_poi_STG_LH.txt','C64_tono_poi_STG_RH.txt',
                        'C65_tono_poi_STG_LH.txt','C65_tono_poi_STG_RH.txt',
                        'C66_tono_poi_STG_LH.txt','C66_tono_poi_STG_RH.txt',
                        'C67_tono_poi_STG_LH.txt',
                        'C68_tono_poi_STG_LH.txt',
                        'C69_tono_poi_STG_LH.txt',
                        'C70_tono_poi_STG_RH.txt',
                        'C71_tono_poi_STG_LH.txt','C71_tono_poi_STG_RH.txt',
                        'C72_tono_poi_STG_LH.txt',
                        'C73_tono_poi_STG_RH.txt',
                        'C74_tono_poi_STG_LH.txt','C74_tono_poi_STG_RH.txt',
                        'C75_tono_poi_STG_LH.txt','C75_tono_poi_STG_RH.txt',
                        'C76_tono_poi_STG_LH.txt','C76_tono_poi_STG_RH.txt',
                        'C77_tono_poi_STG_LH.txt','C77_tono_poi_STG_RH.txt',
                        'C78_tono_poi_STG_LH.txt','C78_tono_poi_STG_RH.txt',
                        'C79_tono_poi_STG_LH.txt','C79_tono_poi_STG_RH.txt'
                        ]
    big_dataset_anat = ['C1_anat_poi_STG_LH.txt','C1_anat_poi_STG_RH.txt',
                        'C2_anat_poi_STG_LH.txt','C2_anat_poi_STG_RH.txt',
                        'C3_anat_poi_STG_LH.txt','C3_anat_poi_STG_RH.txt',
                        'C4_anat_poi_STG_LH.txt','C4_anat_poi_STG_RH.txt',
                        'C5_anat_poi_STG_LH.txt','C5_anat_poi_STG_RH.txt',
                        'C6_anat_poi_STG_LH.txt','C6_anat_poi_STG_RH.txt',
                        'C7_anat_poi_STG_LH.txt','C7_anat_poi_STG_RH.txt',
                        'C8_anat_poi_STG_LH.txt','C8_anat_poi_STG_RH.txt',
                        'C9_anat_poi_STG_LH.txt','C9_anat_poi_STG_RH.txt',
                        'C10_anat_poi_STG_LH.txt','C10_anat_poi_STG_RH.txt',
                        'C11_anat_poi_STG_LH.txt','C11_anat_poi_STG_RH.txt',
                        'C12_anat_poi_STG_LH.txt','C12_anat_poi_STG_RH.txt',
                        'C13_anat_poi_STG_LH.txt','C13_anat_poi_STG_RH.txt',
                        'C14_anat_poi_STG_LH.txt','C14_anat_poi_STG_RH.txt',
                        'C15_anat_poi_STG_LH.txt',
                        'C16_anat_poi_STG_LH.txt',
                        
                        'C18_anat_poi_STG_LH.txt','C18_anat_poi_STG_RH.txt',
                        'C19_anat_poi_STG_LH.txt','C19_anat_poi_STG_RH.txt',
                        'C20_anat_poi_STG_LH.txt','C20_anat_poi_STG_RH.txt',
                        'C21_anat_poi_STG_LH.txt','C21_anat_poi_STG_RH.txt',
                        'C22_anat_poi_STG_LH.txt','C22_anat_poi_STG_RH.txt',
                        'C23_anat_poi_STG_LH.txt','C23_anat_poi_STG_RH.txt',
                        
                        'C25_anat_poi_STG_LH.txt','C25_anat_poi_STG_RH.txt',
                        'C26_anat_poi_STG_LH.txt','C26_anat_poi_STG_RH.txt',
                        'C27_anat_poi_STG_LH.txt','C27_anat_poi_STG_RH.txt',
                        'C28_anat_poi_STG_LH.txt','C28_anat_poi_STG_RH.txt',
                        'C29_anat_poi_STG_RH.txt',
                        'C30_anat_poi_STG_LH.txt',
                        'C31_anat_poi_STG_RH.txt',
                        'C32_anat_poi_STG_LH.txt','C32_anat_poi_STG_RH.txt',
                        'C33_anat_poi_STG_LH.txt','C33_anat_poi_STG_RH.txt',
                        'C34_anat_poi_STG_RH.txt',
                        'C35_anat_poi_STG_RH.txt',
                        'C36_anat_poi_STG_LH.txt',
                        
                        'C38_anat_poi_STG_RH.txt',
                        
                        'C40_anat_poi_STG_RH.txt',
                        'C41_anat_poi_STG_LH.txt','C41_anat_poi_STG_RH.txt',
                        'C42_anat_poi_STG_LH.txt','C42_anat_poi_STG_RH.txt',
                        'C43_anat_poi_STG_LH.txt','C43_anat_poi_STG_RH.txt',
                        'C44_anat_poi_STG_LH.txt','C44_anat_poi_STG_RH.txt',
                        'C45_anat_poi_STG_LH.txt','C45_anat_poi_STG_RH.txt',
                        'C46_anat_poi_STG_LH.txt','C46_anat_poi_STG_RH.txt',
                        'C47_anat_poi_STG_LH.txt','C47_anat_poi_STG_RH.txt',
                        'C48_anat_poi_STG_LH.txt','C48_anat_poi_STG_RH.txt',
                        'C49_anat_poi_STG_LH.txt','C49_anat_poi_STG_RH.txt',
                        'C50_anat_poi_STG_LH.txt','C50_anat_poi_STG_RH.txt',
                        'C51_anat_poi_STG_LH.txt','C51_anat_poi_STG_RH.txt',
                        'C52_anat_poi_STG_LH.txt','C52_anat_poi_STG_RH.txt',
                        'C53_anat_poi_STG_LH.txt','C53_anat_poi_STG_RH.txt',
                        'C54_anat_poi_STG_LH.txt','C54_anat_poi_STG_RH.txt',
                        'C55_anat_poi_STG_LH.txt','C55_anat_poi_STG_RH.txt',
                        'C56_anat_poi_STG_LH.txt','C56_anat_poi_STG_RH.txt',
                        'C57_anat_poi_STG_LH.txt','C57_anat_poi_STG_RH.txt',
                        'C58_anat_poi_STG_LH.txt','C58_anat_poi_STG_RH.txt',
                        'C59_anat_poi_STG_LH.txt','C59_anat_poi_STG_RH.txt',
                        'C60_anat_poi_STG_LH.txt','C60_anat_poi_STG_RH.txt',
                        'C61_anat_poi_STG_LH.txt','C61_anat_poi_STG_RH.txt',
                        'C62_anat_poi_STG_LH.txt','C62_anat_poi_STG_RH.txt',
                        'C63_anat_poi_STG_LH.txt','C63_anat_poi_STG_RH.txt',
                        'C64_anat_poi_STG_LH.txt','C64_anat_poi_STG_RH.txt',
                        'C65_anat_poi_STG_LH.txt','C65_anat_poi_STG_RH.txt',
                        'C66_anat_poi_STG_LH.txt','C66_anat_poi_STG_RH.txt',
                        'C67_anat_poi_STG_LH.txt',
                        'C68_anat_poi_STG_LH.txt',
                        'C69_anat_poi_STG_LH.txt',
                        'C70_anat_poi_STG_RH.txt',
                        'C71_anat_poi_STG_LH.txt','C71_anat_poi_STG_RH.txt',
                        'C72_anat_poi_STG_LH.txt',
                        'C73_anat_poi_STG_RH.txt',
                        'C74_anat_poi_STG_LH.txt','C74_anat_poi_STG_RH.txt',
                        'C75_anat_poi_STG_LH.txt','C75_anat_poi_STG_RH.txt',
                        'C76_anat_poi_STG_LH.txt','C76_anat_poi_STG_RH.txt',
                        'C77_anat_poi_STG_LH.txt','C77_anat_poi_STG_RH.txt',
                        'C78_anat_poi_STG_LH.txt','C78_anat_poi_STG_RH.txt',
                        'C79_anat_poi_STG_LH.txt','C79_anat_poi_STG_RH.txt'
                        ]
    big_dataset_names = ['Subject 1 - LH','Subject 1 - RH',
                         'Subject 2 - LH','Subject 2 - RH',
                         'Subject 3 - LH','Subject 3 - RH',
                         'Subject 4 - LH','Subject 4 - RH',
                         'Subject 5 - LH','Subject 5 - RH',
                         'Subject 6 - LH','Subject 6 - RH',
                         'Subject 7 - LH','Subject 7 - RH',
                         'Subject 8 - LH','Subject 8 - RH',
                         'Subject 9 - LH','Subject 9 - RH',
                         'Subject 10 - LH','Subject 10 - RH',
                         'Subject 11 - LH','Subject 11 - RH',
                         'Subject 12 - LH','Subject 12 - RH',
                         'Subject 13 - LH','Subject 13 - RH',
                         'Subject 14 - LH','Subject 14 - RH',
                         'Subject 15 - LH',
                         'Subject 16 - LH',
                         
                         'Subject 18 - LH','Subject 18 - RH',
                         'Subject 19 - LH','Subject 19 - RH',
                         'Subject 20 - LH','Subject 20 - RH',
                         'Subject 21 - LH','Subject 21 - RH',
                         'Subject 22 - LH','Subject 22 - RH',
                         'Subject 23 - LH','Subject 23 - RH',
                          
                         'Subject 25 - LH','Subject 25 - RH',
                         'Subject 26 - LH','Subject 26 - RH',
                         'Subject 27 - LH','Subject 27 - RH',
                         'Subject 28 - LH','Subject 28 - RH',
                         'Subject 29 - RH',
                         'Subject 30 - LH',
                         'Subject 31 - RH',
                         'Subject 32 - LH','Subject 32 - RH',
                         'Subject 33 - LH','Subject 33 - RH',
                         'Subject 34 - RH',
                         'Subject 35 - RH',
                         'Subject 36 - LH',
                         
                         'Subject 38 - RH',
                         
                         'Subject 40 - RH',
                         'Subject 41 - LH','Subject 41 - RH',
                         'Subject 42 - LH','Subject 42 - RH',
                         'Subject 43 - LH','Subject 43 - RH',
                         'Subject 44 - LH','Subject 44 - RH',
                         'Subject 45 - LH','Subject 45 - RH',
                         'Subject 46 - LH','Subject 46 - RH',
                         'Subject 47 - LH','Subject 47 - RH',
                         'Subject 48 - LH','Subject 48 - RH',
                         'Subject 49 - LH','Subject 49 - RH',
                         'Subject 50 - LH','Subject 50 - RH',
                         'Subject 51 - LH','Subject 51 - RH',
                         'Subject 52 - LH','Subject 52 - RH',
                         'Subject 53 - LH','Subject 53 - RH',
                         'Subject 54 - LH','Subject 54 - RH',
                         'Subject 55 - LH','Subject 55 - RH',
                         'Subject 56 - LH','Subject 56 - RH',
                         'Subject 57 - LH','Subject 57 - RH',
                         'Subject 58 - LH','Subject 58 - RH',
                         'Subject 59 - LH','Subject 59 - RH',
                         'Subject 60 - LH','Subject 60 - RH',
                         'Subject 61 - LH','Subject 61 - RH',
                         'Subject 62 - LH','Subject 62 - RH',
                         'Subject 63 - LH','Subject 63 - RH',
                         'Subject 64 - LH','Subject 64 - RH',
                         'Subject 65 - LH','Subject 65 - RH',
                         'Subject 66 - LH','Subject 66 - RH',
                         'Subject 67 - LH',
                         'Subject 68 - LH',
                         'Subject 69 - LH',
                         'Subject 70 - RH',
                         'Subject 71 - LH','Subject 71 - RH',
                         'Subject 72 - LH',
                         'Subject 73 - RH',
                         'Subject 74 - LH','Subject 74 - RH',
                         'Subject 75 - LH','Subject 75 - RH',
                         'Subject 76 - LH','Subject 76 - RH',
                         'Subject 77 - LH','Subject 77 - RH',
                         'Subject 78 - LH','Subject 78 - RH',
                         'Subject 79 - LH','Subject 79 - RH']
    big_dataset_dupl = ['S','CD',
                        'S','CD',
                        'CD','CD',
                        'S','CD',
                        'S','CD',
                        'S','S',
                        'CD','CD',
                        'CD','PD',
                        'S','S',
                        'S','PD',
                        'CD','PD',
                        'S','S',
                        'S','PD',
                        'CD','CD'
                        'CD',
                        'S',
                        
                        'CD','S',
                        'S','CD',
                        'CD','CD',
                        'CD','CD',
                        'CD','CD',
                        'PD','CD',
                        
                        'S','S',
                        'S','CD',
                        'PD','PD',
                        'S','PD',
                        'CD',
                        'S',
                        'CD',
                        'S','CD',
                        'CD','PD',
                        'CD',
                        'CD',
                        'PD',
                        
                        'PD',
                        
                        'S',
                        'S','CD',
                        'S','CD',
                        'S','S',
                        'S','PD',
                        'CD','CD',
                        'S','PD',
                        'S','S',
                        'S','S',
                        'CD','CD',
                        'S','PD',
                        'S','PD',
                        'PD','S',
                        'S','CD',
                        'PD','PD',
                        'CD','CD',
                        'S','PD',
                        'S','S',
                        'CD','CD',
                        'CD','CD',
                        'PD','CD',
                        'S','PD',
                        'S','S',
                        'S','S',
                        'CD','CD',
                        'S','CD',
                        'S','PD',
                        'CD',
                        'CD',
                        'CD',
                        'PD',
                        'CD',
                        'S',
                        'PD',
                        'PD','CD',
                        'S',
                        'PD',
                        'CD','PD',
                        'CD','CD',
                        'S','S',
                        'S','CD',
                        'PD','PD',
                        'PD','CD'] 
    big_dataset_targets = [0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           1,1,
                           1,
                           1,
                           
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           
                           0,0,
                           0,0,
                           0,0,
                           1,1,
                           1,
                           1,
                           1,
                           1,1,
                           0,0,
                           1,
                           1,
                           1,
                           
                           1,
                           
                           1,
                           1,1,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           0,0,
                           1,1,
                           1,1,
                           1,
                           1,
                           1,
                           1,
                           1,1,
                           1,
                           1,
                           1,1,
                           0,0,
                           0,0,
                           0,0,
                           1,1]  
    
    
    # labels are 0 for controls and 1 for patients
    
    if which_dataset == 'normalized':
        data_tono = np.concatenate((ctl_list_norm, pt_list_norm))
        data_anat = []
        data_dupl = []
        data_names = np.concatenate((ctl_name_norm, pt_name_norm))
        targets = np.concatenate((np.zeros(len(ctl_list_norm)),np.ones(len(pt_list_norm))))
        
    elif which_dataset == 'full':
        data_tono = np.concatenate((ctl_list_full, pt_list_full))
        data_anat = np.concatenate((ctl_anat_full, pt_anat_full))
        data_dupl = np.concatenate((ctl_dupl_full,pt_dupl_full))
        data_names = np.concatenate((ctl_name_full, pt_name_full))
        targets = np.concatenate((np.zeros(len(ctl_list_full)),np.ones(len(pt_list_full))))
        
    elif which_dataset == 'relabelled':
        data_tono = np.concatenate((ctl_list_relabelled, pt_list_relabelled))
        data_anat = np.concatenate((ctl_anat_relabelled, pt_anat_relabelled))
        data_dupl = np.concatenate((ctl_dupl_relab,pt_dupl_relab))
        data_names = np.concatenate((ctl_name_relabelled, pt_name_relabelled))
        targets = np.concatenate((np.zeros(len(ctl_list_relabelled)),np.ones(len(pt_list_relabelled))))
        
    elif which_dataset == 'big_dataset':
        data_tono = big_dataset_tono
        data_anat = big_dataset_anat
        data_dupl = big_dataset_dupl
        data_names = big_dataset_names
        targets = big_dataset_targets
        
    return data_tono, data_anat, data_dupl, data_names, targets